[tool.poetry]
name = "tac-scenario-generator"
version = "0.1.0"
description = "Tool for generating tactical scenarios in a variety of videogames."
authors = ["fildred13 <fildred13@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "tac_scenario_generator"}]

[tool.poetry.dependencies]
python = "^3.10"
pytesseract = "^0.3.10"
PyAutoGUI = "^0.9.54"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
tox = "^4.6.4"
flake8 = "^6.0.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
