---
game_id: cmak
year: 1943
month: july
region: italy
armies:
  Allied:
    Canadian:
      On Map:
        Infantry:
          Infantry:
            - unit_name: Rifle Company
          Air:
            - unit_name: random
              chance_per_unit: 20
              count: 2
          Artillery:
            - unit_name: random
              chance_per_unit: 30
              count: 2
  Axis:
    Italian:
      On Map:
        Infantry:
          Infantry:
            - unit_name: Infantry Company
          Fortification:
            - unit_name: random
              count_min: 2
              count_max: 8
          Artillery:
            - unit_name: Mortar Spotter 81mm
              chance_per_unit: 20
          Air:
            - unit_name: random
              chance_per_unit: 2
          Support:
            - unit_name: random
              count: 4
              chance_per_unit: 25
          Vehicle:
            - unit_name: random
              count: 4
              chance_per_unit: 5
      Reinforce 1:
        Infanrty:
          Armor:
            - unit_name: random
              count: 4
              chance_per_unit: 30
              chance: 30
              all_same: True
